workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    petstore-oas:
        inputs:
            - location: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/candidate-test/candidate-test/petstore-oas
targets:
    petstore:
        target: python
        source: petstore-oas
